### PR TITLE
updated readme  issue19

### LINKED ISSUE #19: add contributing guidelines in readme
hey @kashish-ag   I want to add contributing guidelines  in readme ...that will consist all the steps required during contributing 
hope u got it 
please assign me for this 
thanks :)

### PR DESCRIPTION
**Pull request by Ayan-thecodeking**
fixes #19 
hey @kashish-ag  please review my PR 
let me know if u want any updation 
thanks :)

### CODE REVIEW

**Comment by kashish-ag** [comment]
It has some conflicts Ayan. Please check that and then create pr

**Comment by Ayan-thecodeking** [comment]
> It has some conflicts Ayan. Please check that and then create pr

hey @kashish-ag  see ..is it ok now ?? i have resolved

**Comment by kashish-ag** [comment]
Yeah, it's fine now.

**Comment by Ayan-thecodeking** [comment]
> Yeah, it's fine now.

ok

**Pull request merged**
